// SPIE — Assessment domain objects
// Quiz, Assessment (sommative), and Quality Reports from TQE.

import type { BloomLevel } from './outcomes'

// ─── Quiz ──────────────────────────────────────────────────────────────────────

export type QuestionType =
  | 'qcm'           // Multiple choice
  | 'vrai_faux'     // True / False
  | 'reponse_courte' // Short answer
  | 'appariement'   // Matching
  | 'ordonnancement' // Ordering / sequencing
  | 'developpement'  // Extended response
  | 'calcul'        // Calculation

export interface QuizQuestion {
  id: string
  quizId: string
  type: QuestionType
  enonce: string
  options?: string[]            // For QCM
  reponseCorrecte?: string | string[]
  explication?: string          // Explanation shown after answering
  pointsValeur: number
  niveauBloom?: BloomLevel
  outcomesSpecifiquesIds?: string[]
  difficulte?: 'facile' | 'moyen' | 'difficile'
  ordre: number
  mediasIds?: string[]          // Images, audio, etc.
}

export type QuizStatut = 'brouillon' | 'pret' | 'ouvert' | 'ferme' | 'archive'

export interface Quiz {
  id: string
  lessonId?: string
  sequenceId?: string
  classeId: string
  enseignantId: string
  titre: string
  description?: string
  type: 'formatif' | 'sommatif' | 'diagnostique' | 'pratique'
  questions: QuizQuestion[]
  duree_minutes?: number
  nombreTentatives?: number         // Max attempts per student
  melangQuestions?: boolean
  melangReponses?: boolean
  afficherResultats?: boolean
  langue: 'fr' | 'en'
  outcomesSpecifiquesIds?: string[]
  statut: QuizStatut
  generePar: 'ia' | 'manuel'
  code?: string                     // Join code for live quiz
  createdAt: string
  updatedAt: string
}

// ─── Assessment (Évaluation sommative) ────────────────────────────────────────

export type AssessmentType =
  | 'examen'
  | 'projet'
  | 'presentation'
  | 'portfolio'
  | 'performance'
  | 'observation'
  | 'auto_evaluation'
  | 'par_les_pairs'

export interface AssessmentCriteria {
  id: string
  libelle: string
  description?: string
  poidsPercent: number           // Weight in %
  niveaux: {
    excellent: string
    satisfaisant: string
    en_developpement: string
    insuffisant: string
  }
  outcomesSpecifiquesIds?: string[]
}

export interface Assessment {
  id: string
  sequenceId?: string
  annualPlanId?: string
  classeId: string
  enseignantId: string
  titre: string
  description?: string
  type: AssessmentType
  criteres: AssessmentCriteria[]
  pointsTotal: number
  duree_minutes?: number
  datePrevu?: string
  langue: 'fr' | 'en'
  outcomesSpecifiquesIds: string[]
  competencesIds?: string[]
  instructions?: string
  materielRequis?: string[]
  grille?: string               // Markdown/HTML rubric
  generePar: 'ia' | 'manuel'
  statut: 'brouillon' | 'pret' | 'administre' | 'corrige' | 'archive'
  createdAt: string
  updatedAt: string
}

// ─── Quality Report (TQE) ──────────────────────────────────────────────────────

export type QualitySeverity = 'critique' | 'avertissement' | 'suggestion' | 'info'

export interface QualityIssue {
  code: string                  // Machine-readable code, e.g. "NO_DIFFERENTIATION"
  severite: QualitySeverity
  message: string               // Human-readable explanation
  champ?: string                // Which field is concerned
  suggestion?: string           // How to fix it
}

export interface QualityDimension {
  nom: string
  score: number                 // 0–100
  issues: QualityIssue[]
  poids: number                 // Weight in the overall score
}

export interface QualityReport {
  id: string
  lessonId?: string
  sequenceId?: string
  annualPlanId?: string
  enseignantId: string
  scoreGlobal: number           // 0–100, weighted average
  statut: 'passe' | 'attention' | 'echec'
  dimensions: {
    alignementCurriculaire: QualityDimension
    taxonomieBloom: QualityDimension
    differentiation: QualityDimension
    structure: QualityDimension
    durees: QualityDimension
    langue: QualityDimension
  }
  recommandations: string[]
  issues: QualityIssue[]
  modeleIA?: string             // If AI performed the quality check
  createdAt: string
}

// ─── Professional Reflection ──────────────────────────────────────────────────
// Post-lesson reflection generated by PAE or written by the teacher

export interface TeachingReflection {
  id: string
  lessonId?: string
  sessionId?: string
  enseignantId: string
  type: 'post_lecon' | 'post_sequence' | 'post_trimestre' | 'auto_evaluation'
  // Questions answered
  ceQuiABienFonctionne?: string
  ceQuiEstAModifier?: string
  reactionEleves?: string
  ajustementProchain?: string
  // PAE-generated insights included in this reflection
  insightsInclus?: string[]
  generePar: 'ia' | 'enseignant' | 'mixte'
  createdAt: string
  updatedAt: string
}
